#!/bin/bash
# 安装与Manim兼容的VS Code扩展
code-server --install-extension ms-python.python@2023.20.0
code-server --install-extension njpwerner.autodocstring@0.6.1
code-server --install-extension ms-toolsai.jupyter@2023.10.1100000000

# 配置Python路径确保Manim可被正确识别
mkdir -p /home/${NB_USER}/.vscode
cat <<EOF > /home/${NB_USER}/.vscode/settings.json
{
    "python.defaultInterpreterPath": "/usr/local/bin/python",
    "python.autoComplete.extraPaths": [
        "/home/${NB_USER}/.local/lib/python3.10/site-packages"
    ]
}
EOF
